### ISSUE TITLE
missing <cstdint>

### ISSUE THREAD

**Issue by wojdyr** [mreineck/pocketfft#21]
Hi Martin,
just to let you know, GCC 13 on Ubuntu 24.04 can't find std::uint64_t without `<cstdint>`

    pocketfft_hdronly.h:420:37: error: ‘uint64_t’ is not a member of ‘std’

**Comment by mreineck** [comment]
Thanks for the heads-up! I have included the header now.
Strangely enough, I cnnot reproduce this on Debian with g++ 13; no idea what the difference is.

**Comment by wojdyr** [comment]
Thanks! I see that I get this error only without multi-threading
```
#define POCKETFFT_NO_MULTITHREADING
#include "pocketfft_hdronly.h"
```

**Comment by mreineck** [comment]
Now I can reproduce it, perfect!
